


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."epl_teams" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL
);


ALTER TABLE "public"."epl_teams" OWNER TO "postgres";


ALTER TABLE "public"."epl_teams" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."epl_teams_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."fantasy_squad" (
    "id" bigint NOT NULL,
    "player_id" bigint NOT NULL,
    "fantasy_team_id" bigint
);


ALTER TABLE "public"."fantasy_squad" OWNER TO "postgres";


ALTER TABLE "public"."fantasy_squad" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fantasy_squad_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."fantasy_team" (
    "id" bigint NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"()
);


ALTER TABLE "public"."fantasy_team" OWNER TO "postgres";


ALTER TABLE "public"."fantasy_team" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fantasy_team_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."game_stats" (
    "id" bigint NOT NULL,
    "player_id" bigint NOT NULL,
    "game_week" smallint,
    "goals" smallint,
    "assists" smallint,
    "yellow_cards" smallint,
    "red_cards" smallint,
    "clean_sheets" boolean
);


ALTER TABLE "public"."game_stats" OWNER TO "postgres";


ALTER TABLE "public"."game_stats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_stats_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."players" (
    "id" bigint NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "position" character varying DEFAULT ''::character varying,
    "price" numeric,
    "fpl_id" bigint,
    "team_id" bigint NOT NULL
);


ALTER TABLE "public"."players" OWNER TO "postgres";


ALTER TABLE "public"."players" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."players_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "username" character varying DEFAULT ''::character varying NOT NULL,
    "email" character varying DEFAULT ''::character varying,
    "total_points" smallint,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."epl_teams"
    ADD CONSTRAINT "epl_teams_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fantasy_squad"
    ADD CONSTRAINT "fantasy_squad_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fantasy_team"
    ADD CONSTRAINT "fantasy_team_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_stats"
    ADD CONSTRAINT "game_stats_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_fpl_id_key" UNIQUE ("fpl_id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_team_id_key" UNIQUE ("team_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."fantasy_squad"
    ADD CONSTRAINT "fantasy_squad_fantasy_team_id_fkey" FOREIGN KEY ("fantasy_team_id") REFERENCES "public"."fantasy_team"("id");



ALTER TABLE ONLY "public"."fantasy_squad"
    ADD CONSTRAINT "fantasy_squad_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id");



ALTER TABLE ONLY "public"."fantasy_team"
    ADD CONSTRAINT "fantasy_team_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."game_stats"
    ADD CONSTRAINT "game_stats_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id");



ALTER TABLE ONLY "public"."players"
    ADD CONSTRAINT "players_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."epl_teams"("id");



ALTER TABLE "public"."epl_teams" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fantasy_squad" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."fantasy_team" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."game_stats" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."players" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."epl_teams" TO "anon";
GRANT ALL ON TABLE "public"."epl_teams" TO "authenticated";
GRANT ALL ON TABLE "public"."epl_teams" TO "service_role";



GRANT ALL ON SEQUENCE "public"."epl_teams_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."epl_teams_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."epl_teams_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."fantasy_squad" TO "anon";
GRANT ALL ON TABLE "public"."fantasy_squad" TO "authenticated";
GRANT ALL ON TABLE "public"."fantasy_squad" TO "service_role";



GRANT ALL ON SEQUENCE "public"."fantasy_squad_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."fantasy_squad_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."fantasy_squad_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."fantasy_team" TO "anon";
GRANT ALL ON TABLE "public"."fantasy_team" TO "authenticated";
GRANT ALL ON TABLE "public"."fantasy_team" TO "service_role";



GRANT ALL ON SEQUENCE "public"."fantasy_team_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."fantasy_team_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."fantasy_team_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."game_stats" TO "anon";
GRANT ALL ON TABLE "public"."game_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."game_stats" TO "service_role";



GRANT ALL ON SEQUENCE "public"."game_stats_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."game_stats_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."game_stats_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."players" TO "anon";
GRANT ALL ON TABLE "public"."players" TO "authenticated";
GRANT ALL ON TABLE "public"."players" TO "service_role";



GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."players_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







